version: '3'

volumes:
  pg_data:
  redis_data:
  redis_conf:


services:

  db:
    image: postgres:16
    env_file: ./src/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  redis:
    image: redis:alpine
    restart: always
    env_file: ./src/.env
    volumes:
      - redis_data:/root/redis
      - redis_conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  
  backend:
    build: ./
    env_file: ./src/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - 127.0.0.1:8000:8000