"""empty message

Revision ID: 98880a66b1ac
Revises: 3c3f8629e7a8
Create Date: 2024-05-13 22:08:41.537153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98880a66b1ac'
down_revision: Union[str, None] = '3c3f8629e7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('used_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'used_code')
    # ### end Alembic commands ###
